version: '3'

services:
  php:
    container_name: php-container
    build:
      context: ./config/php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www/api
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    links:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./:/srv/www/api
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin-container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - ${IP}:8000:80
    links:
      - db:db

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - ${IP}:3306:3306
    command: "mysqld --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    volumes:
      - ./data/init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
